# SPDX-FileCopyrightText: Timothée Ravier <tim@siosm.fr>
# SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

# Inspired by https://github.com/coreos/repo-templates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      golang:
        patterns:
          - "*"
    ignore:
      # Block newer versions of k8s until go 1.26 is available in RHEL
      - dependency-name: "k8s.io/api"
        versions: [">=0.35"]
      - dependency-name: "k8s.io/apimachinery"
        versions: [">=0.35"]
      - dependency-name: "sigs.k8s.io/controller-runtime"
        versions: [">=0.23"]
      - dependency-name: "sigs.k8s.io/controller-tools"
        versions: [">=0.20"]
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust:
        patterns:
          - "*"
    ignore:
      - dependency-name: "rand_core"
        # Block newer versions of rand_core, incompatible
        versions: [">=0.7"]
