// SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
//
// SPDX-License-Identifier: MIT

pub const RELATED_IMAGE_COMPUTE_PCRS: &str = "RELATED_IMAGE_COMPUTE_PCRS";
pub const RELATED_IMAGE_TRUSTEE: &str = "RELATED_IMAGE_TRUSTEE";
pub const RELATED_IMAGE_REGISTRATION_SERVER: &str = "RELATED_IMAGE_REGISTRATION_SERVER";
pub const RELATED_IMAGE_ATTESTATION_KEY_REGISTER: &str = "RELATED_IMAGE_ATTESTATION_KEY_REGISTER";
