apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: coreos-trustee
spec:
  runStrategy: Always
  template:
    spec:
      domain:
        features:
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              persistent: true
        devices:
          tpm:
            persistent: true
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          rng: {}
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: containerdisk
        containerDisk:
          image: "quay.io/trusted-execution-clusters/fedora-coreos-kubevirt:clevis-attest-reg"
          imagePullPolicy: IfNotPresent
      - name: cloudinitdisk
        cloudInitConfigDrive:
          secretRef:
            name: coreos-ignition-secret
